### ISSUE TITLE
Link to r-sparsepp in README?

### ISSUE THREAD

**Issue by ChrisMuir** [ChrisMuir/r-fhm#1]
The design/layout of some of the `README` elements are modeled after that of the R package [r-sparsepp](https://github.com/dselivanov/r-sparsepp). With that in mind, and given that the purpose of the packages are very similar, I was considering adding a link to `r-sparsepp` in the `README`...... @dselivanov , would you mind if I did that? Let me know, thanks!

**Comment by dselivanov** [comment]
absolutely! thanks @ChrisMuir for creating this package!

**Comment by ChrisMuir** [comment]
👍 Done!
